name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker build . --file Dockerfile.dev --tag dustinstanley/docker-react-udemy
      - name: Executes the test suite
        run: docker run -e CI=true dustinstanley/docker-react-udemy npm run test -- --coverage
      - name: install eb-cli
        run: pip install awsebcli --upgrade --user
      - name: check eb-cli
        run: ~/.local/bin/eb --version
      - name: write aws config files
        run: bash .github/create-aws-config.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: deploy on live (if master)
        run: ~/.local/bin/eb deploy DockerReactUdemy-env -l $GITHUB_SHA
        if: github.ref == 'refs/heads/master'
      - name: deploy on sandbox (if develop)
        run: ~/.local/bin/eb deploy DockerReactUdemy-env -l $GITHUB_SHA
        if: github.ref == 'refs/heads/develop'
